import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidebar } from "@/components/sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* put the side bar to the left of the content of the page, like twitter */}
        <div className="flex flex-row w-screen h-screen p-0 m-0">
          <div className="static">
            <Sidebar />
          </div>
          <main className="w-full flex p-7">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
